### ISSUE TITLE
Megamenu show/hide behaviour

### ISSUE THREAD

**Issue by schn-mark-plachetta** [digitalnsw/nsw-design-system#124]
If you open a megamenu, click away from it, then try to close the menu, it will instead close then re-open again immediately. This seems counterintuitive.

Also, a megamenu will close itself after 2 clicks (left or right) inside a blank area of the submenu. This can be annoying if you are, for example, trying to select blocks of text that appear inside the submenu.

Seems related to the focus check that is being added here:
https://github.com/digitalnsw/nsw-design-system/blob/v2.10.0/src/components/main-navigation/main-navigation.js#L206

**Steps to reproduce:**
https://nswdesignsystem.surge.sh/components/main-navigation/index.html
1. Click "About DPC", megamenu opens
2. Click away from the menu
3. Click "About DPC" again
4. Megamenu closes then reopens again

.

1. Click "About DPC", megamenu opens
2. Click a blank space inside the menu
3. Click a second time
4. The megamenu closes

**Tested on:**
Firefox 86.0 (64-bit)
Chrome 88.0.4324.190 (Official Build) (64-bit)

**Comment by cdbenj** [comment]
Hi @schn-mark-plachetta thanks for reporting the issue. We'll have a look into this.

**Comment by cdbenj** [comment]
We've fixed the issue @schn-mark-plachetta feel free to update your code to 2.10.1.

Thanks again for reporting the issue.
