### ISSUE TITLE
Integration: Consider altering variable and function names to all prefix with 'nsw'

### ISSUE THREAD

**Issue by horikx** [digitalnsw/nsw-design-system#134]
For assistance with layout I have installed Bootstrap v4 latest,  bootstrap-utilities.scss. This is just a subset of Bootstrap main, but there were quite a few conflicts with bootstrap and its base level variable and function names. If all variables and function names were prefixed, this wouldn't conflict with any assistive libraries.

**Comment by cdbenj** [comment]
Hi @horikx 

Yeah good call, will we look into that.

I would recommend also having a look at the design system's grid and layout and hope that matches your layout needs.

Sample page layout
https://nswdesignsystem.surge.sh/templates/full-width-hero-banner/index.html
https://nswdesignsystem.surge.sh/templates/sidebar-right/index.html

Layout structure
https://nswdesignsystem.surge.sh/styles/layout/index.html

**Comment by horikx** [comment]
Thanks @cdbenj,
I'm more looking for utility classes like d-flex | justify-content-between | align-content-center and their responsive counterparts.

**Comment by cdbenj** [comment]
Hi @horikx 
I see. In that case, we don't have those yet. 
As for the main issue, I will have a chat with the team and assess the priority. We'll let you know further.

**Comment by anna-yeshtukova** [comment]
Hi @horikx. All conflicts with Bootstrap should be fixed now as we had prefixed all our variables and classes with nsw prefix. Thank you for bringing it to our attention.
