### ISSUE TITLE
Mega menu closing issue in Safari

### ISSUE THREAD

**Issue by sesemaya** [digitalnsw/nsw-design-system#151]
Hi there,

This particular issue has the exact same symptoms of first issue reported in #80. It can be reproduced on your demo site: https://nswdesignsystem.surge.sh/components/main-navigation/blank.html.

>In Safari browsers, already opened top-nav items (having sub-navs) do not collapse, on opening another top-nav menu item (having sub-navs).

Although the above issue was fixed in 2.7.0, a new [commit](https://github.com/digitalnsw/nsw-design-system/commit/60d4a4d4c218392731d652bc88329fee879657aa#diff-5ec5a19313cddd5e678d3821929258d649666da7e498d87f8d375b2b64386de2) in 2.10.1 re-introduces this issue back for a different reason.

Safari throws an error on that particular `isNavLinkActive` check because `document.activeElement` returns `body` instead of the actual anchor in Safari.

**Comment by cdbenj** [comment]
Hi @sesemaya 
Thanks for reporting this. You are right looks like it's not completely fixed yet.

**Comment by cdbenj** [comment]
Issue fixed. Replaced `document.activeElement` to `event.target` to accomodate Safari
