### ISSUE TITLE
Repo split?

### ISSUE THREAD

**Issue by JamesDPC** [digitalnsw/nsw-design-system#169]
Hi folks

I see there is now v2.13 in this repo and a v2.14 in https://github.com/digitalnsw/nsw-design-system-v2, which is a bit odd from a version control process.
Is there a reason why a v2 branch couldn't be created in this repo and v2.x releases tagged from that?

Cheers
James

**Comment by schn-mark-plachetta** [comment]
> Does https://nswdesignsystem.surge.sh/ represent v2.14 or v3 ? It has public-sans but that only seems to be applied in docs CSS.

The docs on surge appear to be for v2.14. I feel like this should be made clearer by having the version number appear in the docs.

The docs for v3 are here: https://digitalnsw.github.io/nsw-design-system/

**Comment by JamesDPC** [comment]
Hey TJ

I had a spare moment and knocked this up to get a better overview of the differences between v2.13 and v.2.14.0 as the v2 repo is missing all the tags: https://github.com/digitalnsw/nsw-design-system-v2/tags and the changelog is showing everything back to the initial commit: https://github.com/digitalnsw/nsw-design-system-v2/blob/master/CHANGELOG.md

Links:

+ https://github.com/JamesDPC/nsw-design-system/tree/v2
+ Tags: https://github.com/JamesDPC/nsw-design-system/tags
+ Diff: https://github.com/JamesDPC/nsw-design-system/compare/v2.13.0...v2.14.0

Here's what I did to get one v2 branch:

+ Forked digitalnsw/nsw-design-system on Github to https://github.com/JamesDPC/nsw-design-system  and clone it locally
+ Create a new remote `fork` to my repo: `git remote add fork git@github.com:JamesDPC/nsw-design-system.git`
+ Checkout a new v2 branch `git checkout -b v2`
+ This branch holds v3 work, so reset to the last v2 commit: `git reset --hard 21cb32c94ccd4f3bea2d9e8128a79e30d8fdf69e`
+ Push to my v2 branch: `git push fork v2`
+ Added digitalnsw/nsw-design-system-v2 as a new remote 'theirfork' `git remote add theirfork https://github.com/digitalnsw/nsw-design-system-v2.git`
+ Pull in all v2.x changes after v2.13 to my v2 branch: `git pull theirfork/master`
+ Fetch all tags: `git fetch --all --tags`
+ Push up v2.14 changes to my v2 branch: `git push fork v2`
+ Pushed up 2.14 tags `git push fork v.2.14.0` (ditto 2.14.1 / .2)

Feel free to use this as an example for committing v2 changes to a v2 branch and tagging v2.1x releases from there, or cherry picking v3 commits for backporting (don't know who it works with your npm release publishing).

Cheers
James
