### ISSUE TITLE
The new design system is using scss instead of pure minified css.

### ISSUE THREAD

**Issue by josephtan** [digitalnsw/nsw-design-system#185]
Currently, I am having problems with the new version of the nsw design sytem. 

The new version is using scss instead of minified css and the file structure isn't the same as the previous version.

When I delete the node_modules within my project directory and do a new npm install/yarn install. 

It breaks my project since it was using the previous version.

Can the team working on the nsw design system provide a minified css version and make sure the file structure is the same as the previous version?

**Comment by tjharrop** [comment]
Hi @josephtan, thanks for getting in touch. This is a simple problem to solve :)

3.0 contained new styling, branding, and some breaking changes which we'd reserved for a new major version. We also created version 2.14, which contains the new styling and branding but works with your existing HTML. 

**Options**
Assuming you don't want to change your HTML, you have a couple of options. You can **include the minified CSS from the CDN** by using jsdelivr and including this in your header:
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/nsw-design-system@2/dist/css/main.css">`

**If you're using NPM**, you can install below 3.0.0 (or update your existing dependency)
`npm install nsw-design-system@"<3.0.0"`

You can get compiled CSS in any version of the design system you're getting from NPMm or any version via the CDN. We push `dist/` and `src/` folders.

There's also a chance, if you're using version 2 and referring to the path of the css in node_modules, you experienced a bug yesterday where a version was accidentally launches as 2.14.1 which didn't contain the compiled folder - we've changed our release pipeline with v3.0 and it was a mistake on the team's part - sorry if that's caused any confusion!

**Comment by tjharrop** [comment]
Hi @josephtan  - did everything work out with this? I'll close the issue, but feel free to get in touch if you're still having issues.
