### ISSUE TITLE
Font size xxxl

### ISSUE THREAD

**Issue by JamesDPC** [digitalnsw/nsw-design-system#204]
Hi folks

There is a hint that font-size: xxxl could be an option (or was an option) but the parameters don't allow it to be specified:

https://github.com/digitalnsw/nsw-design-system/blob/master/src/global/scss/base/_mixins.scss#L165

```css
@mixin font-size($size) {
  @if $size != 'xxs' and $size != 'xs' and $size != 'sm' and $size != 'md' and $size != 'lg' and $size != 'xl' and $size != 'xxl' {
    @error 'NSW-DS font-size mixin allows the following values for $sizes: xs, sm, md, lg, xl, xxl, xxxl. You have used "#{$size}"';
  }
```

Support seems to vary: https://developer.mozilla.org/en-US/docs/Web/CSS/font-size#browser_compatibility

Is the inclusion in the error message a typo ?

Cheers
James

**Comment by anna-yeshtukova** [comment]
Hi @JamesDPC. This typo now has been fixed.
