### ISSUE TITLE
Deprecated Dependency

### ISSUE THREAD

**Issue by mrryantch** [digitalnsw/nsw-design-system#213]
Hi Developers of this repo,

We found some deprecated Warning while using this repository. 

![1](https://user-images.githubusercontent.com/25297470/156085591-a8275818-a001-46e2-8fed-cf821b4854c0.jpg)
![2](https://user-images.githubusercontent.com/25297470/156085603-9412f736-667d-4746-b5b3-b695f5c9b410.png)
![3](https://user-images.githubusercontent.com/25297470/156085604-2e7132be-e1b5-46c9-8958-8733918bbf65.png)
![4](https://user-images.githubusercontent.com/25297470/156085609-dbe064b7-b120-428f-975f-40da32e679c2.png)
![5](https://user-images.githubusercontent.com/25297470/156085610-be8f5eb1-375a-49de-b390-556703a15990.png)
![6](https://user-images.githubusercontent.com/25297470/156085611-e350a442-4e33-4b2a-971a-67551384f1be.png)
![7](https://user-images.githubusercontent.com/25297470/156085612-cd8f27bb-d5b1-4d74-80f2-8102796f38bd.png)

**Comment by laurenhitchon** [comment]
Hi @mrryantch,

Thank you for bringing this to our attention. We take deprecated warnings seriously and we appreciate your effort in notifying us about it.

Our team will investigate the warnings and make necessary updates to the repository to ensure it is up-to-date and compatible with the latest standards. We will also check if any dependencies are causing the warnings and take the necessary steps to update or remove them.

Please bear with us as we work on resolving these warnings. We will keep you updated on our progress and let you know when the fixes are pushed to the repository.

**Comment by laurenhitchon** [comment]
Hi @mrryantch,

We have upgraded our dependency node-sass to dart-sass now and converted our exisiting sass code to use the new syntax.
