### ISSUE TITLE
Bug with main navigation, Level 2 link on desktop not working

### ISSUE THREAD

**Issue by JamesDPC** [digitalnsw/nsw-design-system#228]
Hi all

Using https://digitalnsw.github.io/nsw-design-system/components/main-nav/blank.html as an example, specifically the About DPC > first level 2 link, when clicking tgat link on a desktop viewport the link does not work.

![image](https://user-images.githubusercontent.com/69664712/175875122-94aae0b7-f5c1-44b8-81d2-0200720fed16.png)

It looks like the mobile behaviour is being used on desktop. The current workaround is to not use 3rd level items in the main nav component.

### Reproduce

1. Navigate to https://digitalnsw.github.io/nsw-design-system/components/main-nav/blank.html on desktop
2. Click the About DPC link
3. Click the first Level 2 link (href: /nsw-design-system/index.html#level-2)

(I'm using Chrome 103 stable)

### Results

Nothing happens when the Level 2 link is clicked

Dev tools reveals that the hidden level 3 sub nav is getting classes toggled on and off.

### Expected

The Level 2 nav item with a level 3 menu on desktop should take the browser to the link in the href.

The example for v2 at https://nswdesignsystem.surge.sh/components/main-navigation/blank.html correctly navigates on desktop to https://nswdesignsystem.surge.sh/index.html#level-2

On mobile, the v3 example at https://digitalnsw.github.io/nsw-design-system/components/main-nav/blank.html behaves as expected.

Cheers!
James

**Comment by anna-yeshtukova** [comment]
Hi James. Thank you for reporting this issue. We will try to work on it shortly and will keep you posted.

**Comment by laurenhitchon** [comment]
Hi James,

Once again, thank you for reporting the bug with the Level 2 link not working on desktop. We have identified why this is happening and applied a temporary patch to fix the issue, however, we are planning to rewrite/refactor the javascript for the main nav component in the future.

Please let us know if you have any questions or would like more information.
