### ISSUE TITLE
in-page-alert heading level

### ISSUE THREAD

**Issue by eschweitzer78** [digitalnsw/nsw-design-system#240]
Hi team, thanks so much for all the work you do!

We at Salesforce have implemented a Lightning Web Component version of the Design System and while checking accessibility for our own documentation website using Axe-tool, I caught a moderate warning related to the use of heading levels (more exactly decreasing or increasing by more than 1 level) with the in-page-alert.

Recommendations from automated tools are to be taken with a grain of salt, but since the in-page alert is not structural to the document, have you considered replacing the heading markup by something more neutral from a structure point of view, and adding the "nsw-h3" class or similar for styling purposes instead?

Any input appreciated!

**Comment by laurenhitchon** [comment]
Thanks for the suggestion @eschweitzer78, 

After some thought and research we have updated our callout and in-page alert components today, replacing the heading markup with neutral markup `<p>` and using the .nsw-h4 and .nsw-h5 classes for styling purposes. 

Overall, I think it's great that you are considering accessibility and taking the time to ensure that your documentation website is accessible to all users. If you have any further questions or concerns, feel free to reach out again.
