### ISSUE TITLE
Extra curly bracket

### ISSUE THREAD

**Issue by pasankg** [digitalnsw/nsw-design-system#259]
The extra curly bracket needs to be removed from the copy field.

https://github.com/digitalnsw/nsw-design-system/blob/b891496de709493d7750730aa5fd6ada97757a49/src/components/callout/_callout.hbs#L4

**Comment by laurenhitchon** [comment]
Hi @pasankg, 

Because it was originally designed to generate HTML, Handlebars escapes values returned by a {{expression}}. We intentionally did not want Handlebars to escape the json 'copy' value so used the "triple-stash", {{{

https://handlebarsjs.com/guide/#html-escaping
