### ISSUE TITLE
select multiple element not supported in Filters component

### ISSUE THREAD

**Issue by JamesDPC** [digitalnsw/nsw-design-system#284]
Hi, in the filters component multiple select elements aren't triggering filter count updates

- the filter count is not updated in a filter form
- the green checkIcon is not placed on a collapsed section

It looks like this is because getCondition in filters.js doesn't take into account an element with type = 'select-multiple'
See: https://github.com/digitalnsw/nsw-design-system/blob/master/src/components/filters/filters.js#L217

The 'checked' property is being evaluated on the element instead, which returns undefined on a select multiple element.

Looks like it should be using selectedOptions.length to update the total filter count and return selectedOptions.length > 0 to handle checkIcon emplacement on collapsed sections ?

Thanks!
James

**Comment by laurenhitchon** [comment]
Hi James,

Thank you for bringing this to our attention and for proposing a solution. I have reviewed the code in filters.js and have implemented a fix which adds support for multiple select filtering functionality and fixes a minor bug with the single select functionality by simulating the click event.

The updated code has been pushed to the repository, so you should be able to pull the latest changes and test it out. Please let me know if you have any more issues or have any other suggestions.

Thanks again for your contribution to the project!

**Comment by JamesDPC** [comment]
Hi Lauren, thanks for the update. This is working OK when using the multi-select component  at https://digitalnsw.github.io/nsw-design-system/components/select/index.html - as I think the checkboxes in the list are being used to fire the count/status change.

It'd be great if this could work with native `<select multiple>` elements and libraries that manage them like slimselect or even select2 / chosen.

I played around with the filters component and was able to get the status/count updating when the change was fired on a `<select multiple>`  element. The count only changes by one but element.selectedOptions.length returns the number of options selected in the select element, which could be used to increment/decrement the total filter count.


```
// in filters.js:
    static getCondition(element) {
      if (element.type === 'select-multiple') {
        return element.selectedOptions.length > 0;
      } else if (element.type === 'text' || element.type === 'select-one') {
        return element.value !== '';
      }
      return element.checked;
    }
```
https://github.com/digitalnsw/nsw-design-system/blob/master/src/components/filters/filters.js#L216


Thanks
James

**Comment by laurenhitchon** [comment]
Of course @JamesDPC, 

Sorry, I misunderstood your previous comment, unfortunately, at the moment we do not have good support for the native <select> multiple element. However I will be working on adding support for this element and will be implementing this in the upcoming release.

Regarding the update of the status/count when a change is fired on a <select multiple> element, I appreciate your suggestions on using element.selectedOptions.length to determine the number of selected options in the select element and will take that into consideration when implementing this feature.

**Comment by JamesDPC** [comment]
Thanks for responding. It's an edge case - having a huge long list of selectable options (checkboxes or otherwise) in a filter is undesirable but sometimes can't be avoided.
Regarding the filter count, a good example would be selecting multiple regions from a list for filtering - if someone selected four regions should the filter count increase by four, or does it make more sense that when at least one region is selected that the filter count only increases by one?
