### ISSUE TITLE
Bug in multi-select

### ISSUE THREAD

**Issue by JamesDPC** [digitalnsw/nsw-design-system#345]
Hi

There's a minor visual bug in the multi-select component, can be seen at https://digitalnsw.github.io/nsw-design-system/components/select/index.html :

![image](https://github.com/digitalnsw/nsw-design-system/assets/69664712/34c957f3-749d-4fa5-be77-bfd86c95be8c)

I think it might be caused by the first item being used as the label when only one item is selected:
https://github.com/digitalnsw/nsw-design-system/blob/master/src/components/select/select.js#L255

The expected label is the "First lap swimming voucher".

Thanks
James

**Comment by laurenhitchon** [comment]
Hi @JamesDPC,

Thanks again for bringing this issue to our attention! We appreciate your help in improving the multi-select component. I am not sure how we missed this during QA.

I've taken a look at the code you referenced in select.js, and I believe I've identified the issue in the getSelectedOptionText method. Here's the modified method:

`getSelectedOptionText() {
    const noSelectionText = '<span class="multi-select__term">Please select</span>';
    let label = '';
    let ariaLabel = '';
    const count = this.getSelectedOptionCount();

    if (count === this.options.length) {
      label = `All ${this.textSelected}`;
      ariaLabel = `All ${this.textSelected}`;
    } else if (count > 1) {
      label = `${count} ${this.textSelected}`;
      ariaLabel = `${count} ${this.textSelected}, Please select`;
    } else if (count === 1) {
      const selectedOption = this.getSelectedOption();
      label = selectedOption.closest('.nsw-multi-select__option').getAttribute('data-label');
      ariaLabel = `${label}, Please select`;
    } else {
      label = noSelectionText;
      ariaLabel = 'Please select';
    }

    return [label, ariaLabel];
}
`

In this modification, when only one option is selected, it retrieves the label of the selected option and uses that as the label for the multi-select. This change should fix the issue you mentioned.

I have created a pull request to implement this fix. Please feel free to monitor the progress there, and if you have any further feedback or questions, don't hesitate to let us know. Your contribution to improving the NSW Design System is appreciated!

**Comment by JamesDPC** [comment]
Hi Lauren, not a problem :)

I was looking at the PR in https://github.com/digitalnsw/nsw-design-system/pull/346/files and  it looks like it's different to the code snippet above.

I noticed also that in the PR the `ariaLabel` variable is set to `${this.options[0].text}` which will be different to the `label` value?


I think your code snippet above is correct, in that it deals with all items, more than one, one and none.

**Comment by laurenhitchon** [comment]
Hi @JamesDPC, 

Of course! thanks for picking this up. I have now pushed the correct code and merged into master.... I hope :)

https://github.com/digitalnsw/nsw-design-system/blob/master/src/components/select/select.js
