### ISSUE TITLE
Select component error when only 1 option is pre-selected

### ISSUE THREAD

**Issue by JamesDPC** [digitalnsw/nsw-design-system#369]
**Describe the bug**

When a `<select multiple>` element wrapped in js-multi-select loads with one option preselected, Select.initCustomSelect() fails as the dropdown property value has not been set at that point.

**To Reproduce**
1. Load up a page with a select element, wrapped in a js-multi-select per the  Select component documentation
2. Ensure the select element has one option pre-selected e.g (`<option value="foo" selected="selected">bar</option>`)
3. Watch the browser dev console, for an error like `TypeError: this.dropdown.querySelector is not a function`
4. The select element remains invisible as .nsw-multi-select > select = display: none, and no `nsw-multi-select__button` element is created.

**Expected behavior**

The multi-select component should display with the text of the selected option visible.

**Screenshots**

**Desktop (please complete the following information):**

Chrome

**Smartphone (please complete the following information):**

Wasn't tested.

**Additional context**

The issue occurs because getSelectedOption attempts to call this.dropdown.querySelector before this.dropdown value has been assigned:
https://github.com/digitalnsw/nsw-design-system/blob/master/src/components/select/select.js#L306

TypeError: this.dropdown.querySelector is not a function
    at Select.getSelectedOption
    at Select.getSelectedOptionText
    at Select.initButtonSelect
    at Select.initCustomSelect

**Comment by DFSIdigital** [comment]
Hey @JamesDPC,

Thanks for bringing this issue to our attention and providing detailed steps to reproduce it.

After reviewing the problem you've encountered with the <select multiple> element within the js-multi-select, we've identified the specific point at which this.dropdown isn't properly assigned before calling querySelector in the getSelectedOption function is causing the TypeError you've mentioned.

To address this, we are looking into adjusting the timing of this.dropdown assignment within the Select component, ensuring it's properly defined before any queries are made within the initialisation process.

We'll work on a fix for this and provide an update as soon as possible.

If you have any more information or insights that might help in resolving the problem, please feel free to share them.

Thanks again,
Lauren
@laurenhitchon

**Comment by laurenhitchon** [comment]
<p>Hi @JamesDPC,</p>
<p>I wanted to let you know that we've fixed the bug you reported in the &lt;select multiple&gt; element within the js-multi-select feature.</p>
<p>We've&nbsp;refactored the Select and Filters component to address the problem you mentioned. Specifically, we've resolved the issue that was causing Select.initCustomSelect() to fail when the &lt;select&gt; element loaded with preselected options.</p>
<p>Test examples of preselected options <a href="https://digitalnsw.github.io/nsw-design-system/components/select/test.html">https://digitalnsw.github.io/nsw-design-system/components/select/test.html</a></p>

<p>Thanks again for bringing this to our attention. Your feedback is really important in maintaining the quality of our design system.</p>
<p>If you come across anything else, feel free to reach out. We're here to help!</p>
