### ISSUE TITLE
Clearer definition of what a 'light colour' is

### ISSUE THREAD

**Issue by JeffersonBledsoe** [digitalnsw/nsw-design-system#389]
https://digitalnsw.github.io/nsw-design-system/docs/content/design/theming.html outlines various restrictions around colour use in branding . I like how `Brand Dark` tells you which rows can and can't be used. However, `Brand light` only tells you that you should use a `light colour`. We should ideally be giving documentation readers examples of which rows they can/ can't use here too.

**Comment by laurenhitchon** [comment]
Hey @JeffersonBledsoe,

Thanks for getting in touch.

I am happy to update the design theming guidelines to make choosing a Brand Light colour as clear as Brand Dark. In our [full page theming example](https://digitalnsw.github.io/nsw-design-system/templates/theming/full-page.html) we have used row 04 for all of our Brand Light examples so I will update the content to:

**Brand Light** - Your contrasting colour to Brand Dark, used for secondary buttons, light variants of components, backgrounds, and content sections. To ensure the required 4.5:1 contrast ratio for accessibility, this colour must be a light colour. Acceptable colour options for Brand Light include rows 03 or 04 of the NSW Government colour palette.

If you have any more suggestions or notice anything else, feel free to let us know!

**Comment by laurenhitchon** [comment]
Hi @JeffersonBledsoe, 

Just wanted to let you know that we've updated the [design theming guidelines](https://digitalnsw.github.io/nsw-design-system/docs/content/design/theming.html#:~:text=a%20light%20colour.-,Acceptable%20colour%20options%20for%20Brand%20Light%20include%20rows%2003%20or%2004%20of%20the%20NSW%20Government%20colour%20palette.,-Brand%20Supplementary%20%2D%20an) to include the line: 'Acceptable colour options for Brand Light include rows 03 or 04 of the NSW Government colour palette.'

Thanks again for your input, it really helps improve our documentation!
