### ISSUE TITLE
Utility List reference error with share feature

### ISSUE THREAD

**Issue by JamesDPC** [digitalnsw/nsw-design-system#394]
**Describe the bug**

When the "Share this page" button is clicked, a JS error appears in the dev console:

```js
Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
```

**To Reproduce**

1. go to https://digitalnsw.github.io/nsw-design-system/components/utility-list/index.html
2. open dev console in browser
3. Demo & Code tab
4. Click Share this page
5. Observe JS error in console

**Expected behavior**

No JS error

**Screenshots**

n/a

**Desktop (please complete the following information):**

Chrome latest, Firefox latest

**Smartphone (please complete the following information):**

n/a

**Additional context**

this.share is the element li.js-share, when this clicked the component tries to get a button via event.target.closest('a');

It looks like event.target is one of the span elements that are child elements of the `li` element. Neither of these return an element for closest('a').

I think the solution is to find the tooltip `div` containing all the share links and process the events on those?

```js
      this.share.addEventListener('click', event => {
        event.preventDefault();
        const button = event.target.closest('a');
        const social = button.getAttribute('data-social');
        const url = this.getSocialUrl(button, social);
```

**Comment by laurenhitchon** [comment]
Hi @JamesDPC,

Thank you for taking the time to report this issue with the "Share this page" button, and for providing such a clear description of the problem and steps to reproduce it.

We have reviewed the details you provided and acknowledge the JavaScript error that occurs. We are looking into the best approach to address the problem based on your suggestion and will keep you updated on our progress.

**Comment by laurenhitchon** [comment]
Hi @JamesDPC,

We wanted to let you know that we have fixed the bug you reported.

- We continue to use the event listener setup on the parent container. This method guarantees the listener is correctly attached, regardless of when the share buttons are added to the DOM.
- The existing `event.target.closest('a')` function remains effective in identifying whether the clicked item is one of the share buttons.

New Adjustment:

- We've added a check within the function: `if (!button) return`. This ensures that the tooltip or other non share button elements within the tooltip do not trigger the share functionality when clicked.

Thanks again for bringing this to our attention. Please feel free to try out the corrected feature and let us know if everything works as expected or if there are any more concerns.
