### ISSUE TITLE
initSite selectors are too broad, can cause JS errors

### ISSUE THREAD

**Issue by JamesDPC** [digitalnsw/nsw-design-system#395]
**Describe the bug**

In initSite, the selectors are too broad.
https://github.com/digitalnsw/nsw-design-system/blob/master/src/main.js#L40

Consider the link component:

```js
const link = document.querySelectorAll('.js-link')
// ... etc
  if (link) {
    link.forEach((element) => {
      new ExternalLink(element).init()
    })
  }
```

Adding a class "js-link" to any non `<a>` element will cause it to be considered an ExternalLink.

Example:

```html
<em class="js-link">emphasised</em>
```

The ExternalLink component attempts to create linkIcon property and doesn't handle it when this does not exist in the HTML:

https://github.com/digitalnsw/nsw-design-system/blob/master/src/components/link/link.js#L7

this.linkIcon.getAttribute('title') will result in an error, which is not caught, causing later component loading in initSite to fail (e.g navigation)

**To Reproduce**
1. Add some HTML with `<em class="js-link">emphasised</em>` to a page
2. Load the page with the nsw-design-system available
3. Observe the console error

**Expected behavior**

1. JS errors should be caught in each component and not affect other components (try/catch)
2. the selectors should be more restrictive where appropriate, e.g `const link = document.querySelectorAll('a.js-link')`
3. components should test whether properties exist before accessing attributes and similar (linkIcon in this case)

**Screenshots**

n/a

**Desktop (please complete the following information):**

Chrome latest

**Smartphone (please complete the following information):**
not tested

**Additional context**

**Comment by laurenhitchon** [comment]
Hi @JamesDPC,

Thank you for bringing this to our attention and for the detailed bug report. We appreciate the time you took to outline the issue and your suggestions for improvement.

We will review the issue related to the initSite function and its selectors. We aim to implement a fix soon that will address the concerns you've raised regarding the use of non-anchor tags with the js-link class.

We'll keep you updated on our progress.

**Comment by laurenhitchon** [comment]
Hi @JamesDPC,

Several pull requests have been completed and merged in the last 24 hours to address the problems you reported.

Specific fixes have been made to the JavaScript components to ensure better performance and reliability:

- JS errors are now caught in each component to prevent them from affecting other components.
- Selectors have been made more restrictive where appropriate.
- Components now test whether properties exist before accessing attributes and child elements.

We believe these changes should resolve the issue you've raised. Please review the updates and let us know if you encounter any further problems.
