### ISSUE TITLE
Clarify Design/Theming documentation around use of colours on an individual component bases

### ISSUE THREAD

**Issue by JeffersonBledsoe** [digitalnsw/nsw-design-system#399]
Following on from the discussion in https://community.digital.nsw.gov.au/t/clarification-on-handling-of-colours-for-independent-sites/1668/3, I think we should try to clarify the final paragraph in the theming documentation:

> As core styles and components inherit colours from the base colour theme, changing a brand colour will automatically filter down to all instances where that colour is used. Alternatively, colour instances can be updated on an individual basis as required. Where possible, it is indicated in the guidance on the Components page.

I think changing `Alternatively, colour instances can be updated on an individual basis as required.` to say something like `Alternatively, colour instances can be updated on an individual basis within the chosen colour sets as required` will clarify that designers/ developers can't choose any colour at any point for their components and must stick to their chosen palette, even with an independent classification level.

**Comment by oisa** [comment]
Hi @JeffersonBledsoe - thanks so much for offering this update to the documentation content for the NSW Design System. 

We're aligned with the update here for clarification purposes and will include the update in the next batch of documentation updates we have planned.
