### ISSUE TITLE
megaNav lets user open multiple menus

### ISSUE THREAD

**Issue by eschweitzer78** [digitalnsw/nsw-design-system#407]
**Describe the bug**

With a megaNav, opening a menu and then opening another one does not close the first menu. When you click back on the title of the second menu you opened, the previous one is still open.

Also when you click outside the menu area with two menus open, only the one opened last does close.

**To Reproduce**
1. Go to [the mega menu demo](https://digitalnsw.github.io/nsw-design-system/components/main-nav/blank.html)
2. Click on 'About DPC' at the top level
3. Click on 'Updates' at the top level
4. See error, two opened menus are on top of each other
5. Click on 'Updated' or outside the menu area
6. About DPC menu is still open

**Expected behavior**
I assumed you'd want any open menu to be collapsed when another menu is opened.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: safari
 - Version: 17.5

**Comment by laurenhitchon** [comment]
Hi @eschweitzer78 ,

Thank you for bringing this to our attention and for the detailed bug report. We appreciate the time you took to outline the issue.

We aim to implement a fix soon that will address this issue, ensuring that opening a new menu will collapse any previously opened menu. We will keep you updated on our progress and notify you once the fix is deployed.

**Comment by laurenhitchon** [comment]
Hi @eschweitzer78,

A pull request has been completed and merged in the last 24 hours to address the problem you reported in Safari with our Main navigation component.

The fix addresses the issue by changing how the JavaScript code determines if an element is a button in Safari.

Old code:

`const isButton = e.target.getAttribute('role')`

This checks the `role` attribute of the direct target element, which can be unreliable if the target is not the `<a>` element, in this case Safari was finding the span and `role` was null.

New code:

`const isButton = e.target.closest('a').getAttribute('role') === 'button'`

This ensures that the code correctly identifies if the closest `<a>` element has a `role` attribute set to button, making the detection more accurate and reliable.

We believe this fix should resolve the issue you've raised. Please review the update and let us know if you have any more problems.
