### ISSUE TITLE
Date input legend padding - is that desired?

### ISSUE THREAD

**Issue by eschweitzer78** [digitalnsw/nsw-design-system#419]
**Describe the bug**
All form elements but date input (and checkboxes) seem to be using a `label` (vs. a `legend`). Semantically, date input is constructed in the right way with a `fieldset` and hence a `legend`. However `legend`s have a 2px left-right padding whereas label has no padding by default. Checkboxes do set padding to 0 through the `.nsw-form__fieldset legend` CSS rule.

As a result, when building a form with multiple fields including a date input, the label for the latter looks slightly off -- respective to both the fields and the label of other inputs.

Have you considered adjusting padding to 0 as well for a more aesthetically pleasing alignment?

**To Reproduce**
1. Go to the [forms example page](https://digitalnsw.github.io/nsw-design-system/components/form/blank.html)
3. Scroll down to the date input field
4. See how the legend stands out as not being aligned.

**Expected behavior**
An horizontal alignment of all labels in a form would look more pleasing to the eye IMHO.

**Screenshots**
![image](https://github.com/digitalnsw/nsw-design-system/assets/20468027/1166c9c1-ba7c-44c7-9ff3-1d1d649b05f0)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Both Safari and Chrome
 - Version 17.5

**Comment by laurenhitchon** [comment]
Hi @eschweitzer78, 

Again, thank you for bringing this to our attention and for providing such a detailed report. We appreciate your efforts to help improve our components.

We will review this suggestion and consider making adjustments to the padding for legends to improve the visual consistency of our forms. We will keep you updated on our progress.

**Comment by laurenhitchon** [comment]
Hi @eschweitzer78,

A pull request has been completed and merged in the last 24 hours to address the horizontal alignment of the legend element within our date input component.

Specific details about the changes/fix:

- Implemented your suggested fix to remove padding from the legend element. https://github.com/digitalnsw/nsw-design-system/pull/420/files

We believe this fix should resolve the issue you've raised. Please review the update and let us know if you have any more problems.
