### ISSUE TITLE
Reset form functionality sets field to invalid value

### ISSUE THREAD

**Issue by dpi** [digitalnsw/nsw-design-system#434]
**Describe the bug**

When using the Reset / Clear all functionality, such as featured in https://digitalnsw.github.io/nsw-design-system/templates/content/filters.html, a field value should not be set to empty-string if it is not a valid value.

This can cause problems when additional functionality is added to forms, such as auto-submit-on-value change. In this scenario, the form could be sent with an invalid value, then the server returns an error state+message.

**To Reproduce**

- Create a form, in much the same way as https://digitalnsw.github.io/nsw-design-system/templates/content/filters.html
- Add a `<select>`, and do not have an option with empty-string value.

I imagine this is the same for radios.

**Expected behavior**

Provide some kind of other fallback. e.g:

Find `0`, and/or
Select first option and/or
If not required do nothing or unset, and/or
Add some kind of attribute which allows a form field to nominate the default value.

**Screenshots**

None

**Desktop (please complete the following information):**

Fx, but not relevant.

**Comment by laurenhitchon** [comment]
Hi @dpi, 

Thank you for your detailed bug report. We have updated the code to improve the Reset/Clear all functionality in the filters component and address the issues you mentioned.

This update ensures that:

- select-one inputs reset to the first option or the default selected option if specified.
- Checkboxes are reset to their default state.

[fix/issue-434/filters-reset](https://github.com/digitalnsw/nsw-design-system/pull/436/files)

We hope this resolves the issue you encountered. Please let us know if you have any questions or if there's anything we missed.

**Comment by dpi** [comment]
Thanks for this!

Static review of #436 looks on track.

Unfortunately I cant update the Design system for now due to business constraints, but will review when possible.
