### ISSUE TITLE
Chrome warning regarding aria-hidden usage on multiselect

### ISSUE THREAD

**Issue by JeffersonBledsoe** [digitalnsw/nsw-design-system#493]
**Describe the bug**

> Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
Element with focus: input
Ancestor with aria-hidden:  <input aria-hidden=​"true" class=​"nsw-form__checkbox-input js-multi-select__checkbox" type=​"checkbox" id=​"select-all-savings-programs-1-regional-seniors-travel-card-1" value=​"true" checked>​Understand this errorAI

I've yet to look into the implications of this, just filing the issue incase it gets looked at faster than I can!

**To Reproduce**
1. Go to https://designsystem.nsw.gov.au/components/select/index.html
2. Open the "Demo & Code" tab
3. Open the browser development console
4. Scroll down to the multiselect demo
5. Click the box to open the multi-select
6. Click one of the checkboxes within the multi-select

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Google Chrome
 - Version Version 131.0.6778.86 

**Additional context**

**Comment by oisa** [comment]
Thanks @JeffersonBledsoe for reaching out to us and logging the issue!

We've put it on our list to run through and will touch base here for an update so we can both get a fix here.

**Comment by oisa** [comment]
Hey @JeffersonBledsoe - we have a fix for this one where the `aria-hidden` attribute is set dynamically based on if it's visible or not. There are a couple of other items that need to be deployed too so this will be rolled out in the next release alongside these (aiming to be released in the next 24hrs).

Thank you again for finding and reporting the error!
