### ISSUE TITLE
The pagination component has the wrong margin reset

### ISSUE THREAD

**Issue by honzapara** [digitalnsw/nsw-design-system#77]
https://www.digital.nsw.gov.au/design-system/patterns/pagination

The problem is with this rule: 
`.nsw-pagination__item:nth-child(2) {
    margin-left: 0;
}`

This counts with that pagination will always have the directional link ("Back"). This is not always true, though.
If you are on the first page there is no "Back" or "First" text and it results in inconsistent spacing.

**Replicate the problem:**

Try to go to https://nswdesignsystem.surge.sh/components/pagination/index.html, inspect the code and remove first list element: `<li class="nsw-pagination__item nsw-pagination__item--prev-page">`.
Now you should see that space between 1 and 2 is smaller than on other items and design looks broken.

**Comment by cdbenj** [comment]
thanks @honzapara for picking this up. We will be looking into this.

**Comment by cdbenj** [comment]
Fixed in v2.3.1 :)
