### ISSUE TITLE
Sequence (aka stepper) component

### ISSUE THREAD

**Issue by simesy** [digitalnsw/nsw-design-system#78]
I looked through the list of components for a "sequence" component, whereby a user is lead through a series of steps.

**Comment by cdbenj** [comment]
Hi @simesy there's is no existing stepper component. But we are looking into adding more components. If you want this added for a specific use case, please reach out to us [here](https://www.digital.nsw.gov.au/get-involved)

**Comment by simesy** [comment]
Thanks for the pointers - i'll get our team involved.
