### ISSUE TITLE
No licensing specified

### ISSUE THREAD

**Issue by evanbrumley** [digitalnsw/nsw-design-system#79]
Hi there! Would it be possible for a license file (MIT or similar) to be added to this repo? Without one we can't legally use any of this code without express written consent from digitalnsw.

**Comment by cdbenj** [comment]
Hi @evanbrumley thanks for flagging. We'll be adding this to our next release.

**Comment by evanbrumley** [comment]
Awesome, thanks!

**Comment by cdbenj** [comment]
Hi @evanbrumley just want to let you know we've added a MIT LICENSE file in version 2.3.1.

**Comment by evanbrumley** [comment]
Fantastic, thank you!
