### ISSUE TITLE
Main-navigation items collapse & alignment issues

### ISSUE THREAD

**Issue by aleemlatif** [digitalnsw/nsw-design-system#80]
Hi Guys,

Apparently, there are a couple of issues with the main navigation.

1) In Safari browsers,  already opened top-nav items (having sub-navs) do not collapse, on opening another top-nav menu item (having sub-navs).

2) In all browsers, there is an arrow alignment issue on Main Navigation.

URL: http://nswdesignsystem.surge.sh/components/main-navigation/index.html

**Comment by cdbenj** [comment]
Hey @aleemlatif thanks for reporting the issue and I can replicate the issue on my end. We'll log this to our things to fix. Cheers!

**Comment by cdbenj** [comment]
Hi @aleemlatif the issue is fixed
